import Head from 'next/head'
import { Container, Input, Pagination } from '@mantine/core'
import Post from '@/components/Post'
import { useEffect, useState } from 'react'
import { PostData, PostsResponse } from './api/posts'
import api from '@/services/api'
import { IconSearch } from '@tabler/icons-react'
import { debounce } from 'lodash';
import { getPostsInPage, getTotalPages } from '@/services/getPosts'

const getPagedPosts = async (pageIndex: number, searchText: string = ''): Promise<PostsResponse> => {
  const { data: data } = await api.get<PostsResponse>('/api/posts', {
    params: {
      pageIndex,
      searchText
    }
  });

  return data;
};

export async function getStaticProps() {
  const [first_page, total_pages] = await Promise.all([getPostsInPage(1), getTotalPages()]);
  // TODO: segregation of concerns should be used here...
  const data = { ...first_page, ...total_pages };

  return {
    props: {
      data
    }
  }
}

interface PageData {
  pageIndex: number;
  totalPages: number;
}

type PagedPostsResponse = PageData & PostsResponse;

export default function Home({ data }: { data: PagedPostsResponse }) {
  const [posts, setPosts] = useState<PostData[]>(data.items);
  const [searchText, setSearchText] = useState('');
  const [pageData, setPageData] = useState<PageData>({
    pageIndex: 1,
    totalPages: data.totalPages,
  });

  const debouncedSetSearchText = debounce((text: string) => {
    setSearchText(text);
  }, 500);

  useEffect(() => {
    if (pageData.pageIndex === 1 && !searchText) {
      setPosts(data.items);
      setPageData(prev => ({ ...prev, totalPages: data.totalPages }))
    }
    else
      getPagedPosts(pageData.pageIndex, searchText)
        .then(res => {
          setPosts(res.items);
          setPageData(prev => ({ ...prev, totalPages: data.totalPages }));
        });
  }, [pageData.pageIndex, searchText]);

  useEffect(() => {
    if (pageData.pageIndex !== 1)
      setPageData({ ...pageData, pageIndex: 1 })

  }, [pageData.totalPages])

  return (
    <>
      <Head>
        <title>Marco Aurélio Lotz</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>

        <Pagination
          m="lg"
          ml="0"
          mt="0"
          value={pageData.pageIndex}
          onChange={page => setPageData(prev => ({ ...prev, pageIndex: page }))}
          total={pageData.totalPages}
        />
        <Input
          m="lg"
          ml="0"
          maw="400px"
          icon={<IconSearch />}
          placeholder="Search"
          onChange={({ target }) => debouncedSetSearchText(target.value)}
        />
        {posts.map(post => (
          <Post
            key={post.id}
            author={post.author}
            body={post.body}
            category={post.category}
            createdAt={post.createdAt}
            title={post.title} />
        ))}
        <Pagination
          m="lg"
          ml="0"
          mt="0"
          value={pageData.pageIndex}
          onChange={page => setPageData(prev => ({ ...prev, pageIndex: page }))}
          total={pageData.totalPages}
        />
      </Container>
    </>
  )
}
