import Head from 'next/head'
import { Container } from '@mantine/core'
import Post from '@/components/Post'
import { useEffect, useState } from 'react'
import { PostData } from './api/posts'
import api from '@/services/api'

const getPosts = async (pageIndex: number): Promise<PostData[]> => {
  const { data: posts } = await api.get<PostData[]>('/api/posts', {
    params: {
      pageIndex
    }
  });

  return posts;
};

export async function getStaticProps() {
  const initialPosts = await getPosts(1);

  return {
    props: {
      initialPosts
    }
  }
}

interface PageData {
  pageIndex: number;
  totalPages: number;
}

export default function Home({ initialPosts }: { initialPosts: PostData[] }) {
  const [posts, setPosts] = useState<PostData[]>(initialPosts)
  console.log(posts);
  const [pageData, setPageData] = useState<PageData>({
    pageIndex: 1,
    totalPages: 3,
  });

  useEffect(() => {
    if (pageData.pageIndex === 1)
      setPosts(initialPosts);
    else
      getPosts(pageData.pageIndex).then(res => setPosts(res));
  }, [pageData.pageIndex]);

  return (
    <>
      <Head>
        <title>Marco Aurélio Lotz</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        {posts.map(post => (
          <Post
            key={post.id}
            author={post.author}
            body={post.body}
            category={post.category}
            createdAt={post.createdAt}
            title={post.title} />
        ))}
      </Container>
    </>
  )
}
